In [591]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_curve,auc
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ACC
from sklearn.metrics import matthews_corrcoef as MCC
from sklearn.metrics import roc_auc_score as AUC
from sklearn.metrics import f1_score as F1
def auc_roc(y_test1,pre):
    pre=[p for p in pre[:,1]]
    #print(pre)
    fpr,tpr,threshold = roc_curve(y_test1,pre)###计算真正率和假正率
    roc_auc = auc(fpr,tpr)
    #print('roc_auc:%2f'%(roc_auc))
    return roc_auc
def analyze(pre,real):
    AUC_test=auc_roc(real,pre)
    pre=np.argmax(pre,axis=1)
    #print(pre)
    m=confusion_matrix(pre,real, labels=[0,1], sample_weight=None)
    print(m)
    tp, fp, fn, tn = m.ravel()
    TPR=tp/(tp+fn)
    TNR=tn/(tn+fp)
    ACC_test=ACC(real,pre)
    #AUC_test=auc_roc(real,pre)
    MCC_test=MCC(real,pre)
    F1_test=F1(real,pre)
    print('敏感度TPR：%2f，特异度TNR：%2f，ACC：%2f，AUC：%2f,MCC：%2f,F1：%2f'%(TPR,TNR,ACC_test,AUC_test,MCC_test,F1_test))

In [592]:
test=pd.read_csv('DATA_PAPER_Test.CSV')#[mordred]
train=pd.read_csv('DATA_PAPER_TRY_s.CSV')#[mordred
train_labels=list(train['label'])
test_labels=list(test['label'])

In [593]:
train

DPSA1     FNSA3     FPSA1          MW  nCl     FPSA3  nH  \
0     475.028940 -0.113272  0.732040  662.154671    0  0.524023  34   
1     225.887643 -0.056436  0.734507  287.152144    0  0.047168  21   
2     348.335082 -0.040667  0.761853  416.329045    0  0.030081  44   
3     283.981077 -0.045718  0.749907  363.145167    0  0.053892  19   
4      42.076486 -0.051088  0.540324  321.059027    1  0.032098  16   
...          ...       ...       ...         ...  ...       ...  ..   
1060  458.670902 -0.045692  0.744919  627.464493    0  0.038213  65   
1061   65.197994 -0.079354  0.579472  211.074562    0  0.042656   9   
1062  110.340618 -0.093054  0.588110  389.195071    0  0.045955  27   
1063  203.749504 -0.058050  0.708824  263.188529    0  0.041742  25   
1064   43.324992 -0.073126  0.552598  260.024820    2  0.024895  15   

            MOMI-X        MOMI-Y       MOMI-Z  FilterItLogS    SLogP  label  \
0     19725.137889  13418.543982  8552.874662     -3.564678 -7.33270    0.0   
1      2692.835690   1555.870120  1466.746402     -2.655538  1.85030    1.0   
2      6964.828428   5218.124254  2642.278738     -3.524661  5.56060    1.0   
3      4401.184103   2996.689985  2227.535819     -4.827000  1.34412    1.0   
4      3634.542472   2963.782437  1422.467577     -4.160766  3.67390    1.0   
...            ...           ...          ...           ...      ...    ...   
1060  19037.041030  15186.418266  6381.976037     -6.603546  5.55320    1.0   
1061   1916.007065   1611.033972   467.171102     -3.800014  1.61700    0.0   
1062   6579.901082   6271.398751  1567.433464     -1.826444  1.11700    1.0   
1063   2553.972089   2018.893156  1020.624863     -2.864117  2.73260    1.0   
1064   1920.592807   1400.839576   926.865191     -2.710849  1.88400    1.0   

     Unnamed: 13  
0                 
1                 
2                 
3                 
4                 
...          ...  
1060              
1061              
1062              
1063              
1064         NaN  

[1065 rows x 14 columns]

In [736]:
from sklearn.utils import shuffle  
train = shuffle(train) 
train

DPSA1     FNSA3     FPSA1           MW  nCl     FPSA3  nH  \
548  120.422781 -0.070716  0.621201   303.101920    0  0.043581  14   
729  294.813484 -0.050654  0.738945   367.166269    1  0.042345  26   
217  229.086641 -0.119869  0.570664  1891.572232    2  0.051933  99   
39   110.337970 -0.065190  0.572684   460.122356    1  0.038745  25   
687  229.887233 -0.026451  0.696142   356.192235    0  0.028532  28   
..          ...       ...       ...          ...  ...       ...  ..   
347  309.599777 -0.033038  0.737709   386.202799    0  0.037346  30   
880  115.689340 -0.106346  0.671223   131.094629    0  0.055257  13   
727   17.324835 -0.125235  0.517665   305.081871    1  0.054198  16   
964  232.381222 -0.069795  0.699663   309.194008    0  0.043821  27   
710  164.119673 -0.041885  0.664243   263.168543    0  0.028237  22   

           MOMI-X        MOMI-Y        MOMI-Z  FilterItLogS    SLogP  label  \
548   3937.089480   3341.324773    760.855157     -3.233453  1.77370    0.0   
729   7730.446797   7089.332437   1089.565023     -4.578877  2.08780    1.0   
217  80286.107960  57410.524734  41708.109233     -9.614671  1.40960    1.0   
39   11314.707769  10618.772280   2315.612849     -5.596868  4.26732    1.0   
687   5625.440761   5130.083222   1140.786732     -4.269719  4.30920    1.0   
..            ...           ...           ...           ...      ...    ...   
347   7642.638241   7364.808768   1481.933691     -6.444485  4.69260    0.0   
880   1205.470122   1144.894780     77.741396     -0.882639  0.59010    1.0   
727   3783.528075   3005.010611   1073.770269     -3.965526  2.73440    0.0   
964   6343.447761   5844.712094    810.350408     -2.711701  0.63480    1.0   
710   4170.303795   3928.356546    521.273988     -4.117517  3.52050    1.0   

    Unnamed: 13  
548              
729              
217              
39               
687              
..          ...  
347              
880              
727              
964              
710              

[1065 rows x 14 columns]

In [737]:
# t_train=pd.read_csv('../t_2_train.csv')
# train_labels=list(t_train.iloc[:,-1])
# t_test=pd.read_csv('../t_2_test.csv')
# test_labels=list(t_test.iloc[:,-1])

In [738]:
# test=pd.read_csv('test_finger.csv').iloc[:,1:]
# train=pd.read_csv('train_finger_name.csv').iloc[:,1:]

In [739]:
train=train.replace(np.NaN, 0)
test=test.replace(np.NaN, 0)

In [740]:
x_test=np.array(test.iloc[:,1:-2])
x_test.shape

(266, 12)

In [741]:
x_train=np.array(train.iloc[:,:-2])
x_train.shape

(1065, 12)

In [742]:
num_samples=int(x_train.shape[0]/5)
num_samples

213

In [747]:
i=0
rf0=RandomForestClassifier(n_estimators=30,min_samples_leaf=10, max_depth=12,)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= train_labels[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([train_labels[:i*num_samples], train_labels[(i + 1) * num_samples:]], axis=0)
rf0.fit(train_data,train_label)
pre_rf=rf0.predict_proba(train_data)
aa0=analyze(pre_rf,train_label)
pre_rf=rf0.predict_proba(val_data)
aa0=analyze(pre_rf,val_label)
pre_rf0=rf0.predict_proba(x_test)
analyze(pre_rf0,test_labels)


[[214  25]
 [138 475]]
敏感度TPR：0.607955，特异度TNR：0.950000，ACC：0.808685，AUC：0.911585,MCC：0.611542,F1：0.853549
[[ 21  32]
 [ 58 102]]
敏感度TPR：0.265823，特异度TNR：0.761194，ACC：0.577465，AUC：0.555262,MCC：0.030186,F1：0.693878
[[ 22  35]
 [ 86 123]]
敏感度TPR：0.203704，特异度TNR：0.778481，ACC：0.545113，AUC：0.549461,MCC：-0.021322,F1：0.670300


In [748]:

i=2
xg0=XGBClassifier(n_estimators=20,max_depth=5,learning_rate=0.2)#,max_depth=5)#n_estimators=210)#,max_depth=7,learning_rate=0.105)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= train_labels[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([train_labels[:i*num_samples], train_labels[(i + 1) * num_samples:]], axis=0)
xg0.fit(train_data,train_label)
pre_xg=xg0.predict_proba(train_data)
aa0=analyze(pre_xg,train_label)
pre_xg=xg0.predict_proba(val_data)
analyze(pre_xg,val_label)
print('test')
pre_xg0=xg0.predict_proba(x_test)
analyze(pre_xg0,test_labels)

[[275  11]
 [ 82 484]]
敏感度TPR：0.770308，特异度TNR：0.977778，ACC：0.890845，AUC：0.969892,MCC：0.781622,F1：0.912347
[[ 22  31]
 [ 52 108]]
敏感度TPR：0.297297，特异度TNR：0.776978，ACC：0.610329，AUC：0.544672,MCC：0.081804,F1：0.722408
test
[[ 28  46]
 [ 80 112]]
敏感度TPR：0.259259，特异度TNR：0.708861，ACC：0.526316，AUC：0.477203,MCC：-0.034938,F1：0.640000


In [750]:
i=2
gbm0=GradientBoostingClassifier(n_estimators=30)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= train_labels[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([train_labels[:i*num_samples], train_labels[(i + 1) * num_samples:]], axis=0)
gbm0.fit(train_data,train_label)
pre_gbm=gbm0.predict_proba(train_data)
aa0=analyze(pre_gbm,train_label)
pre_gbm=gbm0.predict_proba(val_data)
analyze(pre_gbm,val_label)
print('test')
pre_gbm0=gbm0.predict_proba(x_test)
analyze(pre_gbm0,test_labels)

[[115  10]
 [242 485]]
敏感度TPR：0.322129，特异度TNR：0.979798，ACC：0.704225，AUC：0.853929,MCC：0.421033,F1：0.793781
[[ 10  17]
 [ 64 122]]
敏感度TPR：0.135135，特异度TNR：0.877698，ACC：0.619718，AUC：0.523430,MCC：0.018366,F1：0.750769
test
[[ 16  21]
 [ 92 137]]
敏感度TPR：0.148148，特异度TNR：0.867089，ACC：0.575188，AUC：0.549959,MCC：0.021623,F1：0.708010


In [ ]:
def analyze222(pre,real):
    AUC_test=auc_roc(real,pre)
    pre=np.argmax(pre,axis=1)
    #print(pre)
    m=confusion_matrix(pre,real, labels=[0,1], sample_weight=None)
    print(m)
    tp, fp, fn, tn = m.ravel()
    TPR=tp/(tp+fn)
    TNR=tn/(tn+fp)
    ACC_test=ACC(real,pre)
    #AUC_test=auc_roc(real,pre)
    MCC_test=MCC(real,pre)
    F1_test=F1(real,pre)
    print('敏感度TPR：%2f，特异度TNR：%2f，ACC：%2f，AUC：%2f,MCC：%2f,F1：%2f'%(TPR,TNR,ACC_test,AUC_test,MCC_test,F1_test))

In [725]:
pre=(pre_rf0+pre_gbm0*3+pre_xg0)/3.0
analyze(pre,test_labels)

[[ 55  35]
 [ 53 123]]
敏感度TPR：0.509259，特异度TNR：0.778481，ACC：0.669173，AUC：0.732243,MCC：0.298651,F1：0.736527


In [726]:
a=(pre[:,0]+0.1).reshape(-1,1)
b=(pre[:,1]).reshape(-1,1)

In [727]:
c=np.hstack((a,b))

In [728]:
analyze(c,test_labels)

[[ 60  39]
 [ 48 119]]
敏感度TPR：0.555556，特异度TNR：0.753165，ACC：0.672932，AUC：0.732243,MCC：0.313639,F1：0.732308


In [724]:
pre0=np.argmax(pre_rf0,axis=1)
pre1=np.argmax(pre_gbm0,axis=1)
pre2=np.argmax(pre_xg0,axis=1)
r=0
z=0
toupiao_label=[]
for i in range(266):
    if pre0[i]==pre1[i]==pre2[i]:
        r+=1
        toupiao_label.append(pre0[i])
    else:
        #print(pre0[i],pre1[i],pre2[i])
        #print(count(pre0[i],pre1[i],pre2[i]),exp_test[i]) 
        z+=1
        toupiao_label.append(count(pre0[i],pre1[i],pre2[i]))
print(r,z)
#print(toupiao_label)
analyze111(toupiao_label,test_labels)

215 51
[[ 56  36]
 [ 52 122]]
56 36 52 122
敏感度TPR：0.518519，特异度TNR：0.772152，ACC：0.669173，AUC：0.645335，MCC：0.300105


In [361]:
def count(a,b,c):
    n_0=0
    if a==0:
        n_0+=1
    if b==0:
        n_0+=1
    if c==0:
        n_0+=1
    if n_0>=2:
        return 0
    else:
        return 1 
def analyze111(pre,real):
    m=confusion_matrix( pre,real, labels=[0,1], sample_weight=None)
    print(m)
    tp, fp, fn, tn = m.ravel()
    print(tp, fp, fn, tn)
    TPR=tp/(tp+fn)
    TNR=tn/(tn+fp)
    ACC_test=ACC(real,pre)
    AUC_test=AUC(real,pre)
    MCC_test=MCC(real,pre)
    print('敏感度TPR：%2f，特异度TNR：%2f，ACC：%2f，AUC：%2f，MCC：%2f'%(TPR,TNR,ACC_test,AUC_test,MCC_test))

In [386]:
x_train.shape

(1065, 12)

In [382]:
rf0=RandomForestClassifier(n_estimators=20,min_samples_leaf=12, max_depth=12,min_samples_split=7 )#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10
rf0.fit(x_train,train_labels)
pre_rf_error=rf0.predict_proba(x_train)
aa0=analyze(pre_rf_error,train_labels)

[[264  81]
 [167 553]]
敏感度TPR：0.612529，特异度TNR：0.872240，ACC：0.767136，AUC：0.867334,MCC：0.508443,F1：0.816839


In [389]:
save_rfmodel('error_train',rf0)

In [390]:
import pickle
def save_rfmodel(name,model):
    model_name=name+'.pkl'
    with open(model_name, 'ab') as f:
        pickle.dump(model, f)
def rfmodel_pre(model_name,x,y):
    with open(model_name,'rb') as md:
        model=pickle.load(md)
    pre=prediction(model,x,y)
    return pre

In [391]:
error_index=[]
for i in range(1065):
    if np.argmax(pre_rf_error[i])!=train_labels[i]:
        error_index.append(i)

In [395]:
index_0=[]
for x in error_index:
    if train_labels[x]==0:
        index_0.append(x)

In [402]:
train_er=pd.concat([train.iloc[index_0],train],axis=0)
train_er

DPSA1     FNSA3     FPSA1          MW  nCl     FPSA3  nH  \
19    218.182532 -0.065257  0.658613  418.174001    0  0.036275  26   
20    241.949432 -0.049738  0.744465  259.157229    0  0.036218  21   
24    236.887099 -0.013769  0.715744  306.221626    0  0.039577  28   
34    210.664587 -0.073343  0.672765  396.097404    0  0.056981  21   
42    433.610368 -0.060282  0.661336  872.444578    0  0.048233  56   
...          ...       ...       ...         ...  ...       ...  ..   
1060  458.670902 -0.045692  0.744919  627.464493    0  0.038213  65   
1061   65.197994 -0.079354  0.579472  211.074562    0  0.042656   9   
1062  110.340618 -0.093054  0.588110  389.195071    0  0.045955  27   
1063  203.749504 -0.058050  0.708824  263.188529    0  0.041742  25   
1064   43.324992 -0.073126  0.552598  260.024820    2  0.024895  15   

            MOMI-X        MOMI-Y        MOMI-Z  FilterItLogS   SLogP  label  \
19     5849.959435   4534.975733   3311.601898     -4.767678  2.9708    0.0   
20     3045.331473   2654.578209    781.100311     -4.590797  2.5676    0.0   
24     3285.213059   2471.098694   1580.133671     -6.321486  5.1373    0.0   
34     5477.792392   4555.042044   2057.727497     -3.292180  3.3629    0.0   
42    41687.720632  34558.107638  12930.162069    -10.055760  1.0284    0.0   
...            ...           ...           ...           ...     ...    ...   
1060  19037.041030  15186.418266   6381.976037     -6.603546  5.5532    1.0   
1061   1916.007065   1611.033972    467.171102     -3.800014  1.6170    0.0   
1062   6579.901082   6271.398751   1567.433464     -1.826444  1.1170    1.0   
1063   2553.972089   2018.893156   1020.624863     -2.864117  2.7326    1.0   
1064   1920.592807   1400.839576    926.865191     -2.710849  1.8840    1.0   

     Unnamed: 13  
19                
20                
24                
34                
42                
...          ...  
1060              
1061              
1062              
1063              
1064           0  

[1232 rows x 14 columns]

In [403]:
from sklearn.utils import shuffle  
train1 = shuffle(train_er) 
train1

DPSA1     FNSA3     FPSA1          MW  nCl     FPSA3  nH  \
1064   43.324992 -0.073126  0.552598  260.024820    2  0.024895  15   
75    -57.305804 -0.082667  0.439677  286.050905    1  0.040224  11   
97     58.425218 -0.059542  0.545005  405.135638    1  0.036230  20   
183   281.074967 -0.056844  0.741428  345.114712    0  0.047411  19   
397   197.809661 -0.073420  0.657985  430.235539    0  0.035166  34   
...          ...       ...       ...         ...  ...       ...  ..   
714   108.110115 -0.053201  0.578970  488.117067    2  0.038202  22   
354   278.110834 -0.057798  0.737822  345.114712    0  0.047007  19   
795   110.818368 -0.095132  0.598714  392.199902    0  0.034615  29   
297   124.954445 -0.049373  0.593794  425.161853    1  0.042467  24   
703   117.606037 -0.106528  0.635768  253.117489    0  0.069153  15   

            MOMI-X        MOMI-Y       MOMI-Z  FilterItLogS    SLogP  label  \
1064   1920.592807   1400.839576   926.865191     -2.710849  1.88400    1.0   
75     2942.797702   1741.393239  1604.900592     -4.312727  2.44790    1.0   
97     8669.186900   8301.989179  1719.773252     -5.029580  3.30528    0.0   
183    7150.892776   6960.380362   673.116024     -5.866619  2.89974    0.0   
397    6728.212220   6283.109952  1413.135304     -3.171844  2.71680    0.0   
...            ...           ...          ...           ...      ...    ...   
714    7783.304772   4980.181257  4700.726262     -7.756604  5.49640    0.0   
354    6835.520125   6476.769131   810.070737     -5.866619  2.89974    0.0   
795    5169.205091   4805.870156  1248.762557     -2.797530  1.89570    1.0   
297   12754.172377  12345.798560   988.182013     -5.268777  3.35320    1.0   
703    2418.195737   2021.567300   646.577226     -1.260684 -1.30730    0.0   

     Unnamed: 13  
1064           0  
75                
97                
183               
397               
...          ...  
714               
354               
795               
297               
703               

[1232 rows x 14 columns]

In [409]:
train=train1.replace(np.NaN, 0)
x_train=np.array(train.iloc[:,:-2])

In [410]:
train_labels=list(train1['label'])

In [489]:
rf0=RandomForestClassifier(n_estimators=20)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10
rf0.fit(x_train,train_labels)
pre_rf_error=rf0.predict_proba(x_train)
aa0=analyze(pre_rf_error,train_labels)
pre=rf0.predict_proba(x_test)
analyze(pre,test_labels)

[[598   2]
 [  0 632]]
敏感度TPR：1.000000，特异度TNR：0.996845，ACC：0.998377，AUC：0.999976,MCC：0.996756,F1：0.998420
[[ 63  46]
 [ 45 112]]
敏感度TPR：0.583333，特异度TNR：0.708861，ACC：0.657895，AUC：0.707308,MCC：0.291775,F1：0.711111


In [412]:
num_samples=int(x_train.shape[0]/5)
num_samples

246

In [530]:
i=0
rf0=RandomForestClassifier(n_estimators=20,min_samples_leaf=12, max_depth=12,min_samples_split=7 )#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= train_labels[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([train_labels[:i*num_samples], train_labels[(i + 1) * num_samples:]], axis=0)
rf0.fit(train_data,train_label)
pre_rf=rf0.predict_proba(train_data)
aa0=analyze(pre_rf,train_label)
pre_rf=rf0.predict_proba(val_data)
aa0=analyze(pre_rf,val_label)
pre_rf0=rf0.predict_proba(x_test)
analyze(pre_rf0,test_labels)

[[391  87]
 [ 87 421]]
敏感度TPR：0.817992，特异度TNR：0.828740，ACC：0.823529，AUC：0.905633,MCC：0.646732,F1：0.828740
[[73 48]
 [47 78]]
敏感度TPR：0.608333，特异度TNR：0.619048，ACC：0.613821，AUC：0.665344,MCC：0.227343,F1：0.621514
[[ 71  53]
 [ 37 105]]
敏感度TPR：0.657407，特异度TNR：0.664557，ACC：0.661654，AUC：0.711703,MCC：0.316952,F1：0.700000


In [533]:
i=0
xg0=XGBClassifier(n_estimators=50,max_depth=5,learning_rate=0.05)#,max_depth=5)#n_estimators=210)#,max_depth=7,learning_rate=0.105)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= train_labels[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([train_labels[:i*num_samples], train_labels[(i + 1) * num_samples:]], axis=0)
xg0.fit(train_data,train_label)
pre_xg=xg0.predict_proba(train_data)
aa0=analyze(pre_xg,train_label)
pre_xg=xg0.predict_proba(val_data)
analyze(pre_xg,val_label)
print('test')
pre_xg0=xg0.predict_proba(x_test)
analyze(pre_xg0,test_labels)

[[401  69]
 [ 77 439]]
敏感度TPR：0.838912，特异度TNR：0.864173，ACC：0.851927，AUC：0.940669,MCC：0.703526,F1：0.857422
[[79 49]
 [41 77]]
敏感度TPR：0.658333，特异度TNR：0.611111，ACC：0.634146，AUC：0.681052,MCC：0.269587,F1：0.631148
test
[[ 70  57]
 [ 38 101]]
敏感度TPR：0.648148，特异度TNR：0.639241，ACC：0.642857，AUC：0.712494,MCC：0.282554,F1：0.680135


In [538]:
i=0
gbm0=GradientBoostingClassifier(n_estimators=30)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= train_labels[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([train_labels[:i*num_samples], train_labels[(i + 1) * num_samples:]], axis=0)
gbm0.fit(train_data,train_label)
pre_gbm=gbm0.predict_proba(train_data)
aa0=analyze(pre_gbm,train_label)
pre_gbm=gbm0.predict_proba(val_data)
analyze(pre_gbm,val_label)
print('test')
pre_gbm0=gbm0.predict_proba(x_test)
analyze(pre_gbm0,test_labels)

[[328 101]
 [150 407]]
敏感度TPR：0.686192，特异度TNR：0.801181，ACC：0.745436，AUC：0.836239,MCC：0.491305,F1：0.764319
[[64 47]
 [56 79]]
敏感度TPR：0.533333，特异度TNR：0.626984，ACC：0.581301，AUC：0.635185,MCC：0.161038,F1：0.605364
test
[[ 67  54]
 [ 41 104]]
敏感度TPR：0.620370，特异度TNR：0.658228，ACC：0.642857，AUC：0.711410,MCC：0.274753,F1：0.686469


In [539]:
pre=pre_rf1+pre_rf2+pre_rf0
analyze(pre,test_labels)
pre0=np.argmax(pre_rf0,axis=1)
pre1=np.argmax(pre_rf1,axis=1)
pre2=np.argmax(pre_rf2,axis=1)
r=0
z=0
toupiao_label=[]
for i in range(266):
    if pre0[i]==pre1[i]==pre2[i]:
        r+=1
        toupiao_label.append(pre0[i])
    else:
        #print(pre0[i],pre1[i],pre2[i])
        #print(count(pre0[i],pre1[i],pre2[i]),exp_test[i]) 
        z+=1
        toupiao_label.append(count(pre0[i],pre1[i],pre2[i]))
print(r,z)
#print(toupiao_label)
analyze111(toupiao_label,test_labels)

[[ 69  54]
 [ 39 104]]
敏感度TPR：0.638889，特异度TNR：0.658228，ACC：0.650376，AUC：0.732829,MCC：0.292649,F1：0.691030
175 91
[[ 68  50]
 [ 40 108]]
68 50 40 108
敏感度TPR：0.629630，特异度TNR：0.683544，ACC：0.661654，AUC：0.656587，MCC：0.309567


In [540]:
pre=pre_rf1+pre_gbm0+pre_xg0
analyze(pre,test_labels)
pre0=np.argmax(pre_rf0,axis=1)
pre1=np.argmax(pre_gbm0,axis=1)
pre2=np.argmax(pre_xg0,axis=1)
r=0
z=0
toupiao_label=[]
for i in range(266):
    if pre0[i]==pre1[i]==pre2[i]:
        r+=1
        toupiao_label.append(pre0[i])
    else:
        #print(pre0[i],pre1[i],pre2[i])
        #print(count(pre0[i],pre1[i],pre2[i]),exp_test[i]) 
        z+=1
        toupiao_label.append(count(pre0[i],pre1[i],pre2[i]))
print(r,z)
#print(toupiao_label)
analyze111(toupiao_label,test_labels)

[[ 72  51]
 [ 36 107]]
敏感度TPR：0.666667，特异度TNR：0.677215，ACC：0.672932，AUC：0.737107,MCC：0.338711,F1：0.710963
195 71
[[ 70  51]
 [ 38 107]]
70 51 38 107
敏感度TPR：0.648148，特异度TNR：0.677215，ACC：0.665414，AUC：0.662682，MCC：0.320872
