In [222]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_curve,auc
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ACC
from sklearn.metrics import matthews_corrcoef as MCC
from sklearn.metrics import roc_auc_score as AUC
from sklearn.metrics import f1_score as F1
from sklearn.model_selection import train_test_split
def auc_roc(y_test1,pre):
    pre=[p for p in pre[:,1]]
    #print(pre)
    fpr,tpr,threshold = roc_curve(y_test1,pre)###计算真正率和假正率
    roc_auc = auc(fpr,tpr)
    #print('roc_auc:%2f'%(roc_auc))
    return roc_auc
def analyze(pre,real):
    AUC_test=auc_roc(real,pre)
    pre=np.argmax(pre,axis=1)
    #print(pre)
    m=confusion_matrix(pre,real, labels=[0,1], sample_weight=None)
    print(m)
    tp, fp, fn, tn = m.ravel()
    TPR=tp/(tp+fn)
    TNR=tn/(tn+fp)
    ACC_test=ACC(real,pre)
    #AUC_test=auc_roc(real,pre)
    MCC_test=MCC(real,pre)
    F1_test=F1(real,pre)
    print('敏感度TPR：%2f，特异度TNR：%2f，ACC：%2f，AUC：%2f,MCC：%2f,F1：%2f'%(TPR,TNR,ACC_test,AUC_test,MCC_test,F1_test))
    return ACC_test
import pickle
def save_rfmodel(name,model):
    model_name=name+'.pkl'
    with open(model_name, 'ab') as f:
        pickle.dump(model, f)
def rfmodel_pre(model_name,x,y):
    with open(model_name+'.pkl','rb') as md:
        model=pickle.load(md)
    pre=prediction(model,x,y)
    return pre
def prediction(model,x,y):
    pre_x=model.predict_proba(x)
    analyze(pre_x,y)
    return pre_x

In [223]:
'python -m mordred smiles.mol -o all_finger.csv -3'


'python -m mordred smiles.mol -o all_finger.csv -3'

In [265]:
data=pd.read_csv('data_all.csv')
data=data.replace(np.NaN, 0)

x=np.array(data.iloc[:,:-1])

y=np.array(data.iloc[:,-1])

In [225]:
label_data

SMILES  terminal  t1/2 (h)  \
0     O([C@H]([C@H](NC(c1nc([C@@H](NC[C@@H](C(N)=O)N...                 3.9   
1     c1(nc(cc2ccccc12)C(=O)N([C@@H](CC)C)C)c1c(cccc...                 3.7   
2     [H]N([H])C([C@](CCN1CCCCC1)(CCN(C(C)C)C(C)=O)c...                12.0   
3            Cc1cc(c(cc1C(=O)NC(=N)N)S(=O)(=O)C)n2cccc2                 2.2   
4                    CCCN(CCC)S(=O)(=O)c1ccc(cc1)C(=O)O                 5.9   
...                                                 ...                 ...   
1326  CC(C)[C@@H](CC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3[C...                 9.5   
1327                     CC1=C(C=C(C#N)C(=O)N1)c2ccncc2                 0.8   
1328  c1ccc(cc1)CC[C@H](N[C@@H]1C(N2[C@@H](CCC[N@@]2...                50.6   
1329               c1cc(ccc1O)[C@@H](CN(C)C)C1(CCCCC1)O                 8.4   
1330                            ClCCN(CCCl)P1(=O)NCCCO1                 8.0   

      label  
0         1  
1         1  
2         1  
3         0  
4         1  
...     ...  
1326      1  
1327      0  
1328      1  
1329      1  
1330      1  

[1331 rows x 3 columns]

In [175]:
label=label_data.iloc[:,-1]

In [226]:
label_data=pd.read_csv('finger/smiles_ll.xlsx')
y=np.array(label_data.iloc[:,-1])

In [227]:
d1=pd.read_csv('finger/test_finger.csv')[finger_name]
d2=pd.read_csv('finger/train_finger.csv')[finger_name]
data_0=pd.concat([d1,d2],axis=0)
data_0=data_0.replace(np.NaN, 0)

In [228]:
x=np.array(data_0.iloc[:,:])


In [229]:
#x_train,x_test,y_train,y_test=train_test_split(pre_finger0,y,test_size=0.2,random_state=51,stratify=y)

In [266]:
i=1
with open('model/gbm3.pkl','rb') as md:
        gbm1=pickle.load(md)
pre_gbm1_test=gbm1.predict_proba(x)
analyze(pre_gbm1_test,y)

[[234  77]
 [305 715]]
敏感度TPR：0.434137，特异度TNR：0.902778，ACC：0.712998，AUC：0.763388,MCC：0.390838,F1：0.789183


0.7129977460555973

In [267]:
i=1
with open('model/xg3.pkl','rb') as md:
        xg1=pickle.load(md)
pre_xg1_test=xg1.predict_proba(x)
analyze(pre_xg1_test,y)

[[280  79]
 [259 713]]
敏感度TPR：0.519481，特异度TNR：0.900253，ACC：0.746056，AUC：0.806121,MCC：0.464248,F1：0.808390


0.7460555972952667

In [268]:
i=2
with open('model/rf3.pkl','rb') as md:
        rf2=pickle.load(md)
pre_rf2_test=rf2.predict_proba(x)
analyze(pre_rf2_test,y)

[[309 133]
 [230 659]]
敏感度TPR：0.573284，特异度TNR：0.832071，ACC：0.727273，AUC：0.796431,MCC：0.422503,F1：0.784057


0.7272727272727273

In [269]:
pre=(pre_rf2_test+pre_gbm1_test+pre_xg1_test)/3.0
analyze(pre,y)

[[268  87]
 [271 705]]
敏感度TPR：0.497217，特异度TNR：0.890152，ACC：0.731029，AUC：0.813836,MCC：0.429974,F1：0.797511


0.7310293012772352

In [270]:
f1=pd.read_excel('finger/t_2_smi_test.xlsx')

In [271]:
f1

0                    名称  \
0    c1(nc(cc2ccccc12)C(=O)N([C@@H](CC)C)C)c1c(cccc...               PK11195   
1       c1cc(nc(c1)C(=O)O)Cc2cc(ccc2OCc3ccc(cc3F)Cl)Cl            GSK269984A   
2    [H]N(c1c(c(nc(c2ccnc(c2)c2nnnn2[H])n1)OCCO[H])...           Clazosentan   
3    C(CCNCCN1C(=O)c2c(ccc3ccccc23)C1=O)NCCN1C(=O)c...             Elinafide   
4             C(OP(=O)(NCCBr)NCCBr)c1n(C)c(nc1)N(=O)=O                TH-302   
..                                                 ...                   ...   
262                          CN1N=Nc2c(ncn2C1=O)C(=O)N          Temozolomide   
263  C(CC(C)(N)C)(N[C@H](C(N[C@@H](Cc1c[nH]cn1)C(N[...             Enalkiren   
264  NCCCC[C@H](NC(=O)[C@@H](Cc1cc(Br)c(O)c(Br)c1)N...            Olcegepant   
265   O=N(=O)O[C@H]1CO[C@@H]2[C@@H](CO[C@H]12)ON(=O)=O  Isosorbide Dinitrate   
266  CC([N@+]1([C@@H]2C[C@@H](C[C@@H]1CC2)OC(=O)[C@...          Ciclotropium   

     半衰期实验值  分类标签  
0      3.70     1  
1      8.15     1  
2      2.60     0  
3     52.60     1  
4      1.00     0  
..      ...   ...  
262    1.50     0  
263    1.72     0  
264    2.50     0  
265    1.70     0  
266    3.30     1  

[267 rows x 4 columns]

In [272]:
real_test=list(f1.iloc[:,-1])

In [273]:
smiles=list(f1.iloc[:,0])
len(smiles)

267

In [238]:
smi0=list(label_data.iloc[:,0])
len(smi0)

1331

In [274]:
index=[]
for s in smiles:
    TT=True
    for i in range(len(smi0)):
        if smi0[i]==s:
            #print(f2_smiles[i],s)
            index.append(i)
            TT=False
            break
    if TT:
        x=0
        n=1
        #index.append([560-n,1097-n,1139-n,1278-n][x])
        print(s)
        x+=1         

In [275]:
#pp=np.argmax(pre,axis=1)
test_pp=pre[index]
ll=label[index]

In [276]:
analyze(test_pp,real_test)

[[ 54  24]
 [ 54 135]]
敏感度TPR：0.500000，特异度TNR：0.849057，ACC：0.707865，AUC：0.751106,MCC：0.376728,F1：0.775862


0.7078651685393258

In [253]:
f1['pre']=np.argmax(test_pp,axis=1)

In [264]:
#f1.to_csv('end.csv')

In [263]:
test_smi='[Gd+3].COCCNC(=O)CN(CCN(CCN(CC([O-])=O)CC(=O)NCCOC)CC([O-])=O)CC([O-])=O'
for i in range(len(smi0)):
        if smi0[i]==s:
            print(np.argmax(pre,axis=1)[i])

1


In [258]:
index=[]
for s in smiles:
    TT=True
    x=0
    for i in range(len(smi0)):
        if smi0[i]==s:
            index.append(i)
            x+=1
    if x==2:
        print(s)

len(index)    

[Gd+3].COCCNC(=O)CN(CCN(CCN(CC([O-])=O)CC(=O)NCCOC)CC([O-])=O)CC([O-])=O


268

In [57]:
label_data.to_csv('real_pre.csv')