In [7]:



import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_curve,auc
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ACC
from sklearn.metrics import matthews_corrcoef as MCC
from sklearn.metrics import roc_auc_score as AUC
from sklearn.metrics import f1_score as F1
def auc_roc(y_test1,pre):
    pre=[p for p in pre[:,1]]
    #print(pre)
    fpr,tpr,threshold = roc_curve(y_test1,pre)###计算真正率和假正率
    roc_auc = auc(fpr,tpr)
    #print('roc_auc:%2f'%(roc_auc))
    return roc_auc
def analyze(pre,real):
    AUC_test=auc_roc(real,pre)
    pre=np.argmax(pre,axis=1)
    #print(pre)
    m=confusion_matrix(pre,real, labels=[0,1], sample_weight=None)
    print(m)
    tp, fp, fn, tn = m.ravel()
    TPR=tp/(tp+fn)
    TNR=tn/(tn+fp)
    ACC_test=ACC(real,pre)
    #AUC_test=auc_roc(real,pre)
    MCC_test=MCC(real,pre)
    F1_test=F1(real,pre)
    print('敏感度TPR：%2f，特异度TNR：%2f，ACC：%2f，AUC：%2f,MCC：%2f,F1：%2f'%(TPR,TNR,ACC_test,AUC_test,MCC_test,F1_test))
    return ACC_test

In [6]:
def count(a,b,c):
    n_0=0
    if a==0:
        n_0+=1
    if b==0:
        n_0+=1
    if c==0:
        n_0+=1
    if n_0>=2:
        return 0
    else:
        return 1 
def analyze111(pre,real):
    m=confusion_matrix( pre,real, labels=[0,1], sample_weight=None)
    print(m)
    tp, fp, fn, tn = m.ravel()
    print(tp, fp, fn, tn)
    TPR=tp/(tp+fn)
    TNR=tn/(tn+fp)
    ACC_test=ACC(real,pre)
    AUC_test=AUC(real,pre)
    MCC_test=MCC(real,pre)
    print('敏感度TPR：%2f，特异度TNR：%2f，ACC：%2f，AUC：%2f，MCC：%2f'%(TPR,TNR,ACC_test,AUC_test,MCC_test))

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
data=pd.read_csv('data_all.csv')
data

DPSA1     FNSA3     FPSA1           MW  nCl     FPSA3  nH  \
0     287.629288 -0.109059  0.601570  1414.518432    0  0.061149  84   
1     129.543006 -0.031597  0.608418   352.134241    1  0.028462  21   
2     220.572237 -0.043353  0.667194   407.233955    1  0.031405  34   
3      68.884136 -0.082446  0.566120   320.094311    0  0.044068  16   
4      55.669458 -0.090027  0.555633   285.103479    0  0.032846  19   
...          ...       ...       ...          ...  ...       ...  ..   
1326  458.670902 -0.045692  0.744919   627.464493    0  0.038213  65   
1327   65.197994 -0.079354  0.579472   211.074562    0  0.042656   9   
1328  110.340618 -0.093054  0.588110   389.195071    0  0.045955  27   
1329  203.749504 -0.058050  0.708824   263.188529    0  0.041742  25   
1330   43.324992 -0.073126  0.552598   260.024820    2  0.024895  15   

            MOMI-X        MOMI-Y        MOMI-Z  FilterItLogS    SLogP  label  
0     74808.086673  63632.345988  22018.177370     -2.673257 -7.70358      1  
1      5282.827378   4132.785706   1704.037293     -6.329876  5.42570      1  
2      5792.165230   4784.090259   2622.331064     -4.800029  3.58610      1  
3      4187.577280   3308.329532   1089.951595     -2.804857  0.81249      0  
4      3307.032656   3160.454612    785.256861     -2.816359  2.19550      1  
...            ...           ...           ...           ...      ...    ...  
1326  19037.041030  15186.418266   6381.976037     -6.603546  5.55320      1  
1327   1916.007065   1611.033972    467.171102     -3.800014  1.61700      0  
1328   6579.901082   6271.398751   1567.433464     -1.826444  1.11700      1  
1329   2553.972089   2018.893156   1020.624863     -2.864117  2.73260      1  
1330   1920.592807   1400.839576    926.865191     -2.710849  1.88400      1  

[1331 rows x 13 columns]

In [10]:
data=data.replace(np.NaN, 0)

x=np.array(data.iloc[:,:-1])

y=np.array(data.iloc[:,-1])

In [49]:
index=[]
for i in range(100):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i,stratify=y)
    #rf0=RandomForestClassifier(n_estimators=30,min_samples_leaf=10, max_depth=12)#n_estimators=20,min_samples_leaf=12, max_depth=12,min_samples_split=7 )#, min_samples_split=5,  
                                    # min_samples_leaf=6,max_features=25 , random_state=10
    #rf0=XGBClassifier(n_estimators=20,max_depth=5,learning_rate=0.2)#,max_depth=5)#n_estimators=210)#,max_depth=7,learning_rate=0.105)
    rf0=GradientBoostingClassifier(n_estimators=35)
    rf0.fit(x_train,y_train)
    #pre_rf_train=rf0.predict_proba(x_train)
    #aa0=analyze(pre_rf_train,y_train)
    print(i)
    pre_rf_test=rf0.predict_proba(x_test)
    aa0=analyze(pre_rf_test,y_test)
    if aa0>0.7:
        index.append(i)

0
[[ 35  30]
 [ 73 129]]
敏感度TPR：0.324074，特异度TNR：0.811321，ACC：0.614232，AUC：0.604065,MCC：0.154839,F1：0.714681
1
[[ 43  26]
 [ 65 133]]
敏感度TPR：0.398148，特异度TNR：0.836478，ACC：0.659176，AUC：0.690601,MCC：0.263045,F1：0.745098
2
[[ 48  27]
 [ 60 132]]
敏感度TPR：0.444444，特异度TNR：0.830189，ACC：0.674157，AUC：0.695172,MCC：0.299904,F1：0.752137
3
[[ 39  34]
 [ 69 125]]
敏感度TPR：0.361111，特异度TNR：0.786164，ACC：0.614232，AUC：0.609917,MCC：0.162172,F1：0.708215
4
[[ 39  37]
 [ 69 122]]
敏感度TPR：0.361111，特异度TNR：0.767296，ACC：0.602996，AUC：0.660581,MCC：0.139661,F1：0.697143
5
[[ 35  19]
 [ 73 140]]
敏感度TPR：0.324074，特异度TNR：0.880503，ACC：0.655431，AUC：0.665240,MCC：0.249966,F1：0.752688
6
[[ 52  38]
 [ 56 121]]
敏感度TPR：0.481481，特异度TNR：0.761006，ACC：0.647940，AUC：0.644334,MCC：0.251763,F1：0.720238
7
[[ 49  27]
 [ 59 132]]
敏感度TPR：0.453704，特异度TNR：0.830189，ACC：0.677903，AUC：0.677411,MCC：0.308774,F1：0.754286
8
[[ 42  25]
 [ 66 134]]
敏感度TPR：0.388889，特异度TNR：0.842767，ACC：0.659176，AUC：0.664337,MCC：0.262242,F1：0.746518
9
[[ 53  23]
 [ 55 136]]
敏感度

76
[[ 42  27]
 [ 66 132]]
敏感度TPR：0.388889，特异度TNR：0.830189，ACC：0.651685，AUC：0.640141,MCC：0.245613,F1：0.739496
77
[[ 36  31]
 [ 72 128]]
敏感度TPR：0.333333，特异度TNR：0.805031，ACC：0.614232，AUC：0.634609,MCC：0.156633,F1：0.713092
78
[[ 47  36]
 [ 61 123]]
敏感度TPR：0.435185，特异度TNR：0.773585，ACC：0.636704，AUC：0.655573,MCC：0.221376,F1：0.717201
79
[[ 47  22]
 [ 61 137]]
敏感度TPR：0.435185，特异度TNR：0.861635，ACC：0.689139，AUC：0.732355,MCC：0.332772,F1：0.767507
80
[[ 44  29]
 [ 64 130]]
敏感度TPR：0.407407，特异度TNR：0.817610，ACC：0.651685，AUC：0.667686,MCC：0.247779,F1：0.736544
81
[[ 46  34]
 [ 62 125]]
敏感度TPR：0.425926，特异度TNR：0.786164，ACC：0.640449，AUC：0.647595,MCC：0.227229,F1：0.722543
82
[[ 38  26]
 [ 70 133]]
敏感度TPR：0.351852，特异度TNR：0.836478，ACC：0.640449，AUC：0.694736,MCC：0.216517,F1：0.734807
83
[[ 39  29]
 [ 69 130]]
敏感度TPR：0.361111，特异度TNR：0.817610，ACC：0.632959，AUC：0.648672,MCC：0.201329,F1：0.726257
84
[[ 45  32]
 [ 63 127]]
敏感度TPR：0.416667，特异度TNR：0.798742，ACC：0.644195，AUC：0.669637,MCC：0.233374,F1：0.727794
85
[[ 49  33]
 [ 59

In [50]:
index

[9]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=51,stratify=y)

In [12]:
num_samples=int(x_train.shape[0]/3)
num_samples

354

In [19]:
i=0
rf0=RandomForestClassifier(n_estimators=30,min_samples_leaf=10, max_depth=12,)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
rf0.fit(train_data,train_label)
#pre_rf0_train=rf0.predict_proba(train_data)
#aa0=analyze(pre_rf0_train,train_label)
pre_rf0_val=rf0.predict_proba(val_data)
aa0=analyze(pre_rf0_val,val_label)
pre_rf0_test=rf0.predict_proba(x_test)
analyze(pre_rf0_test,y_test)

[[ 60  39]
 [ 91 164]]
敏感度TPR：0.397351，特异度TNR：0.807882，ACC：0.632768，AUC：0.669918,MCC：0.226149,F1：0.716157
[[ 49  26]
 [ 59 133]]
敏感度TPR：0.453704，特异度TNR：0.836478，ACC：0.681648，AUC：0.724959,MCC：0.316883,F1：0.757835


0.6816479400749064

In [20]:
#save_rfmodel('rf0_no',rf0)

In [23]:
i=1
rf1=RandomForestClassifier(n_estimators=30,min_samples_leaf=10, max_depth=12,)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
rf1.fit(train_data,train_label)
#pre_rf1_train=rf1.predict_proba(train_data)
#aa0=analyze(pre_rf1_train,train_label)
pre_rf1_val=rf1.predict_proba(val_data)
aa0=analyze(pre_rf1_val,val_label)
pre_rf1_test=rf1.predict_proba(x_test)
analyze(pre_rf1_test,y_test)

[[ 58  45]
 [ 82 169]]
敏感度TPR：0.414286，特异度TNR：0.789720，ACC：0.641243，AUC：0.671529,MCC：0.219612,F1：0.726882
[[ 52  28]
 [ 56 131]]
敏感度TPR：0.481481，特异度TNR：0.823899，ACC：0.685393，AUC：0.731016,MCC：0.327180,F1：0.757225


0.6853932584269663

In [24]:
#save_rfmodel('rf1_no',rf1)

In [583]:
i=2
rf2=RandomForestClassifier(n_estimators=30,min_samples_leaf=10, max_depth=12,)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
rf2.fit(train_data,train_label)
#pre_rf2_train=rf2.predict_proba(train_data)
#aa0=analyze(pre_rf2_train,train_label)
pre_rf2_val=rf2.predict_proba(val_data)
aa0=analyze(pre_rf2_val,val_label)
pre_rf2_test=rf2.predict_proba(x_test)
analyze(pre_rf2_test,y_test)

[[ 59  44]
 [ 81 170]]
敏感度TPR：0.421429，特异度TNR：0.794393，ACC：0.646893，AUC：0.639186,MCC：0.232332,F1：0.731183
[[ 60  36]
 [ 48 123]]
敏感度TPR：0.555556，特异度TNR：0.773585，ACC：0.685393，AUC：0.737829,MCC：0.336634,F1：0.745455
[[ 53  24]
 [ 55 135]]
敏感度TPR：0.490741，特异度TNR：0.849057，ACC：0.704120，AUC：0.750349,MCC：0.368136,F1：0.773639


0.704119850187266

In [46]:
i=0
xg0=XGBClassifier(n_estimators=20,max_depth=5,learning_rate=0.05)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
xg0.fit(train_data,train_label)
pre_xg0_train=xg0.predict_proba(train_data)
aa0=analyze(pre_xg0_train,train_label)
pre_xg0_val=xg0.predict_proba(val_data)
aa0=analyze(pre_xg0_val,val_label)
pre_xg0_test=xg0.predict_proba(x_test)
analyze(pre_xg0_test,y_test)


[[182  21]
 [ 98 409]]
敏感度TPR：0.650000，特异度TNR：0.951163，ACC：0.832394，AUC：0.913455,MCC：0.650210,F1：0.872999
[[ 59  51]
 [ 92 152]]
敏感度TPR：0.390728，特异度TNR：0.748768，ACC：0.596045，AUC：0.611588,MCC：0.149077,F1：0.680089
[[ 51  39]
 [ 57 120]]
敏感度TPR：0.472222，特异度TNR：0.754717，ACC：0.640449，AUC：0.692202,MCC：0.235620,F1：0.714286


0.6404494382022472

In [48]:
#save_rfmodel('xg0_no',xg0)

In [47]:
i=1
xg1=XGBClassifier(n_estimators=20,max_depth=5,learning_rate=0.05)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
xg1.fit(train_data,train_label)
pre_xg1_train=xg1.predict_proba(train_data)
aa0=analyze(pre_xg1_train,train_label)
pre_xg1_val=xg1.predict_proba(val_data)
aa0=analyze(pre_xg1_val,val_label)
pre_xg1_test=xg1.predict_proba(x_test)
analyze(pre_xg1_test,y_test)


[[182  17]
 [109 402]]
敏感度TPR：0.625430，特异度TNR：0.959427，ACC：0.822535，AUC：0.905580,MCC：0.640422,F1：0.864516
[[ 50  35]
 [ 90 179]]
敏感度TPR：0.357143，特异度TNR：0.836449，ACC：0.646893，AUC：0.659846,MCC：0.221601,F1：0.741201
[[ 48  27]
 [ 60 132]]
敏感度TPR：0.444444，特异度TNR：0.830189，ACC：0.674157，AUC：0.714506,MCC：0.299904,F1：0.752137


0.6741573033707865

In [44]:
i=2
xg2=XGBClassifier(n_estimators=20,max_depth=5,learning_rate=0.05)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
xg2.fit(train_data,train_label)
pre_xg2_train=xg2.predict_proba(train_data)
aa0=analyze(pre_xg2_train,train_label)
pre_xg2_val=xg2.predict_proba(val_data)
aa0=analyze(pre_xg2_val,val_label)
pre_xg2_test=xg2.predict_proba(x_test)
analyze(pre_xg2_test,y_test)

[[186  32]
 [105 387]]
敏感度TPR：0.639175，特异度TNR：0.923628，ACC：0.807042，AUC：0.887685,MCC：0.600066,F1：0.849616
[[ 45  39]
 [ 95 175]]
敏感度TPR：0.321429，特异度TNR：0.817757，ACC：0.621469，AUC：0.603939,MCC：0.159972,F1：0.723140
[[ 56  34]
 [ 52 125]]
敏感度TPR：0.518519，特异度TNR：0.786164，ACC：0.677903，AUC：0.721756,MCC：0.316337,F1：0.744048


0.6779026217228464

In [49]:
#save_rfmodel('xg2_no',xg2)

In [34]:
i=0
gbm0=GradientBoostingClassifier(n_estimators=20)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
gbm0.fit(train_data,train_label)
pre_gbm0_train=gbm0.predict_proba(train_data)
aa0=analyze(pre_gbm0_train,train_label)
pre_gbm0_val=gbm0.predict_proba(val_data)
aa0=analyze(pre_gbm0_val,val_label)
pre_gbm0_test=gbm0.predict_proba(x_test)
analyze(pre_gbm0_test,y_test)


[[140  26]
 [140 404]]
敏感度TPR：0.500000，特异度TNR：0.939535，ACC：0.766197，AUC：0.837616,MCC：0.507520,F1：0.829569
[[ 55  45]
 [ 96 158]]
敏感度TPR：0.364238，特异度TNR：0.778325，ACC：0.601695，AUC：0.644146,MCC：0.156613,F1：0.691466
[[ 53  31]
 [ 55 128]]
敏感度TPR：0.490741，特异度TNR：0.805031，ACC：0.677903，AUC：0.690426,MCC：0.312610,F1：0.748538


0.6779026217228464

In [35]:
#save_rfmodel('gbm0_no',gbm0)

In [36]:
i=1
gbm1=GradientBoostingClassifier(n_estimators=20)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
gbm1.fit(train_data,train_label)
##pre_gbm1_train=gbm1.predict_proba(train_data)
#aa0=analyze(pre_gbm1_train,train_label)
pre_gbm1_val=gbm1.predict_proba(val_data)
aa0=analyze(pre_gbm1_val,val_label)
pre_gbm1_test=gbm1.predict_proba(x_test)
analyze(pre_gbm1_test,y_test)

[[ 44  34]
 [ 96 180]]
敏感度TPR：0.314286，特异度TNR：0.841121，ACC：0.632768，AUC：0.649483,MCC：0.183333,F1：0.734694
[[ 47  20]
 [ 61 139]]
敏感度TPR：0.435185，特异度TNR：0.874214，ACC：0.696629，AUC：0.723038,MCC：0.350249,F1：0.774373


0.6966292134831461

In [40]:
i=2
gbm2=GradientBoostingClassifier(n_estimators=20)#, min_samples_split=5,  
                                # min_samples_leaf=6,max_features=25 , random_state=10)
val_data= x_train[i*num_samples:(i+1)*num_samples,:]
val_label= y_train[i * num_samples:(i + 1) * num_samples]
train_data=np.concatenate([x_train[:i*num_samples,:],x_train[(i+1)*num_samples:,:]],axis=0)
train_label = np.concatenate([y_train[:i*num_samples], y_train[(i + 1) * num_samples:]], axis=0)
gbm2.fit(train_data,train_label)
pre_gbm2_train=gbm2.predict_proba(train_data)
aa0=analyze(pre_gbm2_train,train_label)
pre_gbm2_val=gbm2.predict_proba(val_data)
aa0=analyze(pre_gbm2_val,val_label)
pre_gbm2_test=gbm2.predict_proba(x_test)
analyze(pre_gbm2_test,y_test)

[[165  52]
 [126 367]]
敏感度TPR：0.567010，特异度TNR：0.875895，ACC：0.749296，AUC：0.819132,MCC：0.472837,F1：0.804825
[[ 46  41]
 [ 94 173]]
敏感度TPR：0.328571，特异度TNR：0.808411，ACC：0.618644，AUC：0.619693,MCC：0.155568,F1：0.719335
[[ 52  29]
 [ 56 130]]
敏感度TPR：0.481481，特异度TNR：0.817610，ACC：0.681648，AUC：0.717068,MCC：0.319312,F1：0.753623


0.6816479400749064

In [41]:
save_rfmodel('gbm2_no',gbm2)

In [327]:
pre=(pre_rf1_test+pre_gbm1_test+pre_xg1_test)/3.0
analyze(pre,y_test)

[[ 51  25]
 [ 57 134]]
敏感度TPR：0.472222，特异度TNR：0.842767，ACC：0.692884，AUC：0.726590,MCC：0.342597,F1：0.765714


0.6928838951310862

In [328]:
pre0=np.argmax(pre_rf1_test,axis=1)
pre1=np.argmax(pre_gbm1_test,axis=1)
pre2=np.argmax(pre_xg1_test,axis=1)
r=0
z=0
toupiao_label=[]
for i in range(267):
    if pre0[i]==pre1[i]==pre2[i]:
        r+=1
        toupiao_label.append(pre0[i])
    else:
        #print(pre0[i],pre1[i],pre2[i])
        #print(count(pre0[i],pre1[i],pre2[i]),exp_test[i]) 
        z+=1
        toupiao_label.append(count(pre0[i],pre1[i],pre2[i]))
print(r,z)
#print(toupiao_label)
analyze111(toupiao_label,y_test)

216 51
[[ 49  26]
 [ 59 133]]
49 26 59 133
敏感度TPR：0.453704，特异度TNR：0.836478，ACC：0.681648，AUC：0.645091，MCC：0.316883


In [2]:
import pickle
def save_rfmodel(name,model):
    model_name=name+'.pkl'
    with open(model_name, 'ab') as f:
        pickle.dump(model, f)
def rfmodel_pre(model_name,x,y):
    with open(model_name,'rb') as md:
        model=pickle.load(md)
    pre=prediction(model,x,y)
    return pre

In [611]:
save_rfmodel('rf1',rf2)
save_rfmodel('xg1',xg1)
save_rfmodel('gbm1',gbm1)
